import controlP5.*;
ControlP5 cp5;
 
void setup() {
  size(800, 640);
  cp5 = new ControlP5(this);
 
  // add a dropdownlist at position (50,100)
  DropdownList droplist = cp5.addDropdownList("Escolha sua cidade:").setPosition(50, 100);
 
  // add items to the dropdownlist
  
  droplist.addItem("Água Branca ", 1);
  droplist.addItem("Aguiar", 2);
  droplist.addItem("Alagoa Grande", 3);
  droplist.addItem("Alagoa Nova", 4);
  droplist.addItem("Alagoinha", 5);
  droplist.addItem("Alcantil", 6);
  droplist.addItem("Algodão de Jandaíra", 7);
  droplist.addItem("Alhandra", 8);
  droplist.addItem("Amparo", 9);
  droplist.addItem("Aparecida", 10);
  droplist.addItem("Araçagi", 11);
  droplist.addItem("Arara", 12);
  droplist.addItem("Araruna", 13);
  droplist.addItem("Areia", 14);
  droplist.addItem("Areia de Baraúnas", 15);
  droplist.addItem("Areial", 16);
  droplist.addItem("Aroeiras", 17);
  droplist.addItem("Assunção", 18);
  droplist.addItem("Baía da Traição", 19);
  droplist.addItem("Bananeiras", 20);
  droplist.addItem("Baraúna", 21);
  droplist.addItem("Barra de Santa Rosa", 22);
  droplist.addItem("Barra de Santana", 23);
  droplist.addItem("Barra de São Miguel", 24);
  droplist.addItem("Bayeux", 24);
  droplist.addItem("Belém", 25);
  droplist.addItem("Belém do Brejo do Cruz", 26);
  droplist.addItem("Bernardino Batista", 27);
  droplist.addItem("Boa Ventura", 28);
  droplist.addItem("Boa Vista", 29);
  droplist.addItem("Bom Jesus", 30);
  droplist.addItem("Bom Sucesso", 31);
  droplist.addItem("Bonito de Santa Fé", 32);
  droplist.addItem("Boqueirão", 33);
  droplist.addItem("Borborema", 34);
  droplist.addItem("Brejo do Cruz", 35);
  droplist.addItem("Brejo dos Santos", 36);
  droplist.addItem("Caaporã", 37);
  droplist.addItem("Cabaceiras", 38);
  droplist.addItem("Cabedelo", 39);
  droplist.addItem("Cachoeira dos Índios", 40);
  droplist.addItem("Cacimba de Areia", 41);
  droplist.addItem("Cacimba de Dentro", 42);
  droplist.addItem("Cacimbas", 43);
  droplist.addItem("Caiçara", 44);
  droplist.addItem("Cajazeiras", 45);
  droplist.addItem("Cajazeirinhas", 46);
  droplist.addItem("Caldas Brandão", 47);
  droplist.addItem("Camalaú", 48);
  droplist.addItem("Campina Grande", 49);
  droplist.addItem("Campo de Santana", 50);
  droplist.addItem("Capim", 51);
  droplist.addItem("Caraúbas", 52);
  droplist.addItem("Carrapateira", 53);
  droplist.addItem("Casserengue", 54);
  droplist.addItem("Catingueira", 55);
  droplist.addItem("Catolé do Rocha", 56);
  droplist.addItem("Caturité", 57);
  droplist.addItem("Conceição", 58);
  droplist.addItem("Condado", 59);
  droplist.addItem("Conde", 60);
  droplist.addItem("Congo", 61);
  droplist.addItem("Coremas", 62);
  droplist.addItem("Coxixola", 63);
  droplist.addItem("Cruz do Espírito Santo", 64);
  droplist.addItem("Cubati", 65);
  droplist.addItem("Cuité", 66);
  droplist.addItem("Cuité de Mamanguape", 67);
  droplist.addItem("Cuitegi", 68);
  droplist.addItem("Curral de Cima", 69);
  droplist.addItem("Curral Velho", 70);
  droplist.addItem("Damião", 71);
  droplist.addItem("Desterro", 72);
  droplist.addItem("Diamante", 73);
  droplist.addItem("Dona Inês", 74);
  droplist.addItem("Duas Estradas", 75);
  droplist.addItem("Emas", 76);
  droplist.addItem("Esperança", 77);
  droplist.addItem("Fagundes", 78);
  droplist.addItem("Frei Martinho", 79);
  droplist.addItem("Gado Bravo", 80);
  droplist.addItem("Guarabira", 81);
  droplist.addItem("Gurinhém", 82);
  droplist.addItem("Gurjão", 83);
  droplist.addItem("Ibiara", 84);
  droplist.addItem("Igaracy", 85);
  droplist.addItem("Imaculada", 86);
  droplist.addItem("Ingá", 87);
  droplist.addItem("Itabaiana", 88);
  droplist.addItem("Itaporanga", 89);
  droplist.addItem("Itapororoca", 90);
  droplist.addItem("Itatuba", 91);
  droplist.addItem("Jacaraú", 92);
  droplist.addItem("Jericó", 93);
  droplist.addItem("João Pessoa", 94);
  droplist.addItem("Joca Claudino", 95);
  droplist.addItem("Juarez Távora", 96);
  droplist.addItem("Juazeirinho", 97);
  droplist.addItem("Junco do Seridó", 98);
  droplist.addItem("Juripiranga", 99);
  droplist.addItem("Juru", 100);
  droplist.addItem("Lagoa", 101);
  droplist.addItem("Lagoa de Dentro", 102);
  droplist.addItem("Lagoa Seca", 103);
  droplist.addItem("Lastro", 104);
  droplist.addItem("Livramento", 105);
  droplist.addItem("Logradouro", 106);
  droplist.addItem("Lucena", 107);
  droplist.addItem("Mãe d'Água", 108);
  droplist.addItem("Malta", 109);
  droplist.addItem("Mamanguape", 110);
  droplist.addItem("Manaíra", 111);
  droplist.addItem("Marcação", 112);
  droplist.addItem("Mari", 113);
  droplist.addItem("Marizópolis", 114);
  droplist.addItem("Massaranduba", 115);
  droplist.addItem("Mataraca", 116);
  droplist.addItem("Matinhas", 117);
  droplist.addItem("Mato Grosso", 118);
  droplist.addItem("Maturéia", 119);
  droplist.addItem("Mogeiro", 120);
  droplist.addItem("Montadas", 121);
  droplist.addItem("Monte Horebe", 122);
  droplist.addItem("Monteiro", 123);
  droplist.addItem("Mulungu", 124);
  droplist.addItem("Natuba", 125);
  droplist.addItem("Nazarezinho", 126);
  droplist.addItem("Nova Floresta", 127);
  droplist.addItem("Nova Olinda", 128);
  droplist.addItem("Nova Palmeira", 129);
  droplist.addItem("Olho d'Água", 130);
  droplist.addItem("Olivedos", 131);
  droplist.addItem("Ouro Velho", 2);
  droplist.addItem("Parari", 2);
  droplist.addItem("Passagem", 2);
  droplist.addItem("Patos", 2);
  droplist.addItem("Paulista", 2);
  droplist.addItem("Pedra Branca", 2);
  droplist.addItem("Pedra Lavrada", 2);
  droplist.addItem("Pedras de Fogo", 2);
  droplist.addItem("Pedro Régis", 2);
  droplist.addItem("Piancó", 2);
  droplist.addItem("Picuí", 2);
  droplist.addItem("Pilar", 2);
  droplist.addItem("Pilões", 2);
  droplist.addItem("Pilõezinhos", 2);
  droplist.addItem("Pirpirituba", 2);
  droplist.addItem("Pitimbu", 2);
  droplist.addItem("Pocinhos", 2);
  droplist.addItem("Poço Dantas", 2);
  droplist.addItem("Poço de José de Moura", 2);
  droplist.addItem("Pombal", 2);
  droplist.addItem("Prata", 2);
  droplist.addItem("Princesa Isabel", 2);
  droplist.addItem("Puxinanã", 2);
  droplist.addItem("Queimadas", 2);
  droplist.addItem("Quixaba", 2);
  droplist.addItem("Remígio", 2);
  droplist.addItem("Riachão", 2);
  droplist.addItem("Riachão do Bacamarte", 2);
  droplist.addItem("Riachão do Poço", 2);
  droplist.addItem("Riacho de Santo Antônio", 2);
  droplist.addItem("Riacho dos Cavalos", 2);
  droplist.addItem("Rio Tinto", 2);
  droplist.addItem("Salgadinho", 2);
  droplist.addItem("Salgado de São Félix", 2);
  droplist.addItem("Santa Cecília", 2);
  droplist.addItem("Santa Cruz", 2);
  droplist.addItem("Santa Helena", 2);
  droplist.addItem("Santa Inês", 2);
  droplist.addItem("Santa Luzia", 2);
  droplist.addItem("Santa Rita", 2);
  droplist.addItem("Santa Teresinha", 2);
  droplist.addItem("Santana de Mangueira", 2);
  droplist.addItem("Santana dos Garrotes", 2);
  droplist.addItem("Santo André", 2);
  droplist.addItem("São Bentinho", 2);
  droplist.addItem("São Bento", 2);
  droplist.addItem("São Domingos", 2);
  droplist.addItem("São Domingos do Cariri", 2);
  droplist.addItem("São Francisco", 2);
  droplist.addItem("São João do Cariri", 2);
  droplist.addItem("São João do Rio do Peixe", 2);
  droplist.addItem("São João do Tigre", 2);
  droplist.addItem("São José da Lagoa Tapada", 2);
  droplist.addItem("São José de Caiana", 2);
  droplist.addItem("São José de Espinharas", 2);
  droplist.addItem("São José de Piranhas", 2);
  droplist.addItem("São José de Princesa", 2);
  droplist.addItem("São José do Bonfim", 2);
  droplist.addItem("São José do Brejo do Cruz", 2);
  droplist.addItem("São José do Sabugi", 2);
  droplist.addItem("São Mamede", 2);
  droplist.addItem("São Miguel de Taipu", 2);
  droplist.addItem("São Sebastião de Lagoa de Roça", 2);
  droplist.addItem("São Sebastião do Umbuzeiro", 2);
  droplist.addItem("Seridó", 2);
  droplist.addItem("Serra Branca", 2);
  droplist.addItem("Serra Grande", 2);
  droplist.addItem("Serra da Raiz", 2);
  droplist.addItem("Serra Redonda", 2);
  droplist.addItem("Serraria", 2);
  droplist.addItem("Sertãozinho", 2);
  droplist.addItem("Sobrado", 2);
  droplist.addItem("Solânea", 2);
  droplist.addItem("Sossêgo", 2);
  droplist.addItem("Tacima", 2);
  droplist.addItem("Tavares", 2);
  droplist.addItem("Tenório", 2);
  droplist.addItem("Triunfo", 2);
  droplist.addItem("Várzea", 2);
  droplist.addItem("Vieirópolis", 2);
  droplist.addItem("Zabelê", 2);
  
}
 
void draw() {
  background(128);
  // controlp5 autodraw is on by default (if you use the default JAVA2D renderer)
  // this means the gui is automatically drawn at the end
}
 
// controlEvent monitors clicks on the gui
void controlEvent(ControlEvent theEvent) {
  if (theEvent.isGroup()) {
    println(theEvent.getGroup() + " => " + theEvent.getGroup().getValue());
  }
}

